messages:
  response:
    start: "Привет! Запусти команду /help, чтобы узнать, что я умею."
    welcome: "Добро пожаловать! Запусти команду /help, чтобы узнать, что я умею."
    unknown_command: "Неизвестная команда."
    unknown_ask: "Не понял. Можешь запустить команду /help, чтобы узнать, что я умею."
    text_only: "Я понимаю только текст."
    how_much_callories: "Сколько в этом продукте киллокаллорий?"
    invalid_text: "Текст должен содержать только назавание одного продукта или блюда, без знаков препинания или спецсимволов."
    product_exists: "Такой продукт уже есть в базе!"
    product_added: "Добавил продукт в базу!"
    start_lunch: "Окей, давай уточним состав приема пищи. Перечисляй продукты или блюда из базы по одному."
    rest_lunch: "Прибавил продукт %s с %s ккал! Есть еще продукты? Пиши его название, если да, либо \"нет\", если таковых не осталось."
    stop_lunch: "Прием пищи зафиксирован! Ты потребила %s киллокаллорий."
    what_product: "О каком продукте идет речь?"
    product_not_exists: "Такого продукта нет в базе!"
    product_callories: "В продукте %s %s килокалорий."
    day_report: "За этот день ты потребила %s калорий. В среднем %s за прием пищи."
    week_report: "За прошедшую неделю ты потребила %s калорий. В среднем %s за прием пищи."
    month_report: "За прошедший месяц ты потребила %s калорий. В среднем %s за прием пищи."
    ask_list: "Список команд:\nДобавь продукт в базу\nЗафиксируй прием пищи\nСколько калорий в продукте\nОтчет за день\nОтчет за неделю\nОтчет за месяц"
  error:
    failed_start: "Не удалось запустить бота, попробуй позже."
    user_param_error: "Не удалось обработать сообщение, попробуй позже."
    insert_food_error: "Не удалось добавить продукт в базу. Попробуй в другой раз."
    count_callories_error: "Не удалось посчитать каллории этого приема пищи. Попробуй позже."
    report_error_not_found: "Не было приемов пищи!"
    find_callories_error: "Не удалось найти калорийность продукта в базе. Попробуй позже."
    find_product_name_error:  "Не удалось выполнить поиск продукта в базе. Попробуй позже."