messages:
  response:
    start: "Привет! Запусти команду /help, чтобы узнать, что я умею."
    welcome: "Добро пожаловать! Запусти команду /help, чтобы узнать, что я умею."
    unknow_command: "Неизвестная команда."
    unknow_ask: "Не понял. Можешь запустить команду /help, чтобы узнать, что я умею."
    text_only: "Я понимаю только текст."
    how_much_callories: "Сколько в этом продукте киллокаллорий?"
  error:
    failed_start: "Не удалось запустить бота, попробуй позже."
    user_param_error: "Не удалось обработать сообщение, попробуй позже."
    insert_food_error: "Не удалось добавить продукт в базу. Попробуй в другой раз."
    count_callories_error: "Не удалось посчитать каллории этого приема пищи. Попробуй позже."
    report_error_not_found: "Не было приемов пищи!"
    find_callories_error: "Не удалось найти калорийность продукта в базе. Попробуй позже."
    find_product_name_error:  "Не удалось выполнить поиск продукта в базе. Попробуй позже."